[features]
seeds = false
[programs.localnet]
nft_minting = "G17ksqA9jiLUvEAtQg5B4kGJGAPCC9EtkgPP9w28JFRV"

[programs.devnet]
nft_minting = "G17ksqA9jiLUvEAtQg5B4kGJGAPCC9EtkgPP9w28JFRV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/alex/blockchain/Keys/alex.json"

#[provider]
#cluster = "localnet"
#wallet = "/home/alex/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
